<a href="https://colab.research.google.com/github/tahminahasan/Workflow-ML/blob/main/Column_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Column Transformer

In [82]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [83]:
df = pd.read_csv('/content/covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [84]:
df.shape

(100, 6)

In [85]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [86]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [87]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [89]:
X_train

    age  gender  fever   cough     city
30   15    Male  101.0    Mild    Delhi
26   19  Female  100.0    Mild  Kolkata
96   51  Female  101.0  Strong  Kolkata
3    31  Female   98.0    Mild  Kolkata
28   16    Male  104.0    Mild  Kolkata
..  ...     ...    ...     ...      ...
32   34  Female  101.0  Strong    Delhi
64   42    Male  104.0    Mild   Mumbai
41   82    Male    NaN    Mild  Kolkata
4    65  Female  101.0    Mild   Mumbai
10   75  Female    NaN    Mild    Delhi

[80 rows x 5 columns]

In [90]:
from sklearn.compose import ColumnTransformer

In [91]:
# Creating a column transformer to preprocess multiple columns in one step
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever'] ),
     ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']) ,
     ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'] )

], remainder= 'passthrough')

# Transformer 1: Apply SimpleImputer to the 'fever' column to fill missing values
# Transformer 2: Apply OrdinalEncoder to the 'cough' column
# Transformer 3: Apply OneHotEncoder to 'gender' and 'city' columns

    # drop='first' avoids the dummy variable trap (drops first category of each)
    # sparse_output=False returns a dense NumPy array instead of a sparse matrix

# Leave any other columns (like 'age') unchanged and pass them through

In [92]:
transformer.fit_transform(X_train).shape

(80, 7)

In [93]:
transformer.transform(X_test).shape

(20, 7)